Tugas 16 - Elequent ORM/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function () {
    Route::resource('cast','CastController');
    Route::resource('profile','ProfileController')->only(['index','update']);
    Route::resource('komentar','KomentarController')->only(['store']);
});
Route::resource('film','FilmController');
Route::resource('genre','GenreController');

Route::get('/','HomeController@index');
Route::get('/register','AuthController@register');
Route::post('/kirim','AuthController@kirim');
Route::view('/data-table','table.data-table');
Route::view('/table','table.table');


//CRUD CAST
// Route::get('/cast','CastController@index');
// Route::get('/cast/create','CastController@create');
// Route::post('/cast','CastController@store');
// Route::get('/cast/{cast_id}','CastController@show');
// Route::get('/cast/{cast_id}/edit','CastController@edit');
// Route::put('/cast/{cast_id}','CastController@update');
// Route::delete('/cast/{cast_id}','CastController@destroy');



// CRUD
// Route::view('/admin2','layouts.admin');
// Route::view('/register','register');
// Route::view('/welcome','welcome');
// Route::get('/','');


Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Tugas 16 - Elequent ORM/app/Film.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Film extends Model
{
    protected $table = 'film';
    protected $fillable = ['judul','ringkasan','tahun','poster','genre_id'];

    public function genre()
    {
        return $this->belongsTo('App\Genre','genre_id');
    }
    public function komentar()
    {
        return $this->hasMany('App\Komentar');
    }
}

Tugas 16 - Elequent ORM/app/Http/Controllers/FilmController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Film;
use App\Genre;
use File;


class FilmController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth')->except(['index','show']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $film = Film::all();
        return view('film.index', compact('film'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $genres = Genre::all();
        return view('film.create', compact('genres'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request 
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request -> validate([
            'judul' => 'required',
            'ringkasan' => 'required',
            'tahun' => 'required',
            'genre_id' => 'required',
            'poster' => 'required|mimes:png,jpg,jpeg|max:2048',
        ]);
        $fileName = time().'.'.$request->poster->extension();

        $film = new Film;
        $film->judul = $request->judul;
        $film->ringkasan = $request->ringkasan;
        $film->tahun = $request->tahun;
        $film->genre_id = $request->genre_id;
        $film->poster = $fileName;
        $film->save();

        $request->poster->move(public_path('image'), $fileName);
        return redirect('/film');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $film = Film::findOrFail($id);
        return view('film.detail', compact('film'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $genre = Genre::all();
        $film = Film::findOrFail($id);
        return view('film.edit', compact('film','genre'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request -> validate([
            'judul' => 'required',
            'ringkasan' => 'required',
            'tahun' => 'required',
            'genre_id' => 'required',
            'poster' => 'mimes:png,jpg,jpeg|max:2048',
        ]);
        $film = Film::findOrFail($id);

        if ($request->has('poster')) {
            // $post_.delete();
            $path="image/";
            File::delete($path.$film->poster);
            // $poster = $request->poster;
            // $new_gambar = time().'-'.$gambar->getClientOriginalName();
            // $gambar->move('upload/post/',$new_gambar);
            $fileName = time().'.'.$request->poster->extension();
            $request->poster->move(public_path('image'), $fileName);
            $film_data = [
                'judul' => $request->judul,
                'ringkasan' => $request->ringkasan,
                'tahun' => $request->tahun,
                'genre_id' => $request->genre_id,
                'poster' => $fileName,
            ];
        }else {
            $film_data = [
                'judul' => $request->judul,
                'ringkasan' => $request->ringkasan,
                'tahun' => $request->tahun,
                'genre_id' => $request->genre_id,
            ];
        }
        // $film->tags()->sync($request->tags);
        $film->update($film_data);
        return redirect('/film');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $film = Film::findOrFail($id);
        $path="image/";
        File::delete($path.$film->poster);
        $film->delete();
        return redirect('/film');
    }
}

Tugas 16 - Elequent ORM/resources/views/film/create.blade.php
@extends('layouts.admin')

@section('title')
    Halaman Tambah Film
@endsection

@section('isi')
    <h1>Masukkan Film!</h1>
    <form action="/film" method="post" enctype="multipart/form-data">
        @csrf
        <label for="judul">Judul : </label>
        <input type="text" value="{{ old('judul') }}" name="judul" id="judul"><br><br>
        @error('judul')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <label for="ringkasan">Ringkasan : </label><br>
        <textarea name="ringkasan" id="ringkasan" cols="30" rows="10">{{ old('ringkasan') }}</textarea><br>
        @error('ringkasan')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <label for="tahun">Tahun : </label>
        <input type="text" value="{{ old('tahun') }}" name="tahun" id="tahun"><br><br>
        @error('tahun')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <label for="genre">Genre : </label>
        <select name="genre_id" id="genre">
            <option value="">-- Pilih Genre --</option>
            @foreach ($genres as $genre)
                <option value="{{ $genre->id }}">{{ $genre->nama }}</option>
            @endforeach
        </select>
        @error('genre')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <br>
        <label for="poster">Poster : </label>
        <input type="file" name="poster" id="poster"><br><br>
        @error('poster')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <br>
        <button type="submit" class="btn btn-primary">Tambah</button>
    </form>
@endsection

Tugas 16 - Elequent ORM/resources/views/film/detail.blade.php
@extends('layouts.admin')

@section('title')
    Halaman Detail Film
@endsection

@section('isi')
    <img src="{{ asset('image/' . $film->poster) }}" width="300px" alt="">
    <h1>{{ $film->judul }}</h1>
    <p>Nama : {{ $film->judul }}</p>
    <p>ringkasan : {{ $film->ringkasan }}</p>
    <p>tahun : {{ $film->tahun }}</p>
    <p>genre_id : {{ $film->genre_id }}</p>
    <br>
    <h1>DAFTAR KOMENTAR</h1>
    <hr>
    @forelse ($film->komentar as $item)
        <div class="card">
            <h5 class="card-header">{{ $item->user->name }}</h5>
            <div class="card-body">
                <h5 class="card-title">Point : {{ $item->point }}</h5>
                <p class="card-text">{{ $item->content }}</p>
            </div>
        </div>

    @empty
        <h5>TIDAK ADA KOMENTAR</h5>
    @endforelse

    @auth
        <form action="/komentar" method="post">
            @csrf
            <div class="form-group">
                <input type="hidden" name="film_id" value="{{ $film->id }}" id="">
                <label for="point">Point : </label><br>
                <input type="number" name="point" id="point"><br>
                <label for="content">Isi Komentar : </label><br>
                <textarea name="content" id="content"></textarea><br>
                @error('content')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <input type="submit" value="Add Komentar" class="btn btn-primary">
        </form>

        <a href="/film" class="btn btn-info">Kembali</a>
    @endauth
@endsection

Tugas 16 - Elequent ORM/resources/views/film/edit.blade.php
@extends('layouts.admin')

@section('title')
    Edit Film {{ $film->nama }}
@endsection

@section('isi')
    <h1>Edit Film!</h1>
    <form action="/film/{{ $film->id }}" method="post" enctype="multipart/form-data">
        @csrf
        @method('put')
        <label for="judul">Judul : </label>
        <input type="text" value="{{ $film->judul }}" name="judul" id="judul"><br><br>
        @error('judul')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <label for="ringkasan">ringkasan : </label><br>
        <textarea name="ringkasan" id="ringkasan" cols="30" rows="10">{{ $film->ringkasan }}</textarea>
        @error('ringkasan')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <br>
        <label for="tahun">tahun : </label>
        <input type="text" value="{{ $film->tahun }}" name="tahun" id="tahun"><br>
        @error('tahun')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <label for="genre">Genre</label>
        <select name="genre_id" id="genre">
            @foreach ($genre as $item)
                @if ($item->id === $film->genre_id)
                    <option value="{{ $item->id }}" selected>{{ $item->nama }}</option>
                @else
                    <option value="{{ $item->id }}">{{ $item->nama }}</option>
                @endif
            @endforeach
        </select>
        <br>
        <label for="poster">Poster : </label>
        <img src="{{ asset('image/' . $film->poster) }}" width="300px" alt=""><br><br>
        <input type="file" name="poster" id="poster">
        @error('poster')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <br><br>
        <button type="submit">Edit</button>
    </form>
@endsection

Tugas 16 - Elequent ORM/resources/views/film/index.blade.php
@extends('layouts.admin')

@section('title')
    Halaman Film
@endsection

@section('isi')
    @auth
        <a href="/film/create" class="btn btn-primary mb-3">Tambah Film</a>
    @endauth
    <div class="row">
        @forelse ($film as $item)
            <div class="col-4">
                <div class="card">
                    <img src="{{ asset('image/' . $item->poster) }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5>{{ $item->judul }}</h5><br>
                        <span class="badge badge-warning">{{ $item->genre->nama }}</span>
                        <p class="card-text">{{ Str::limit($item->ringkasan, 10) }}</p>
                        @auth
                            <form action="{{ route('film.destroy', $item->id) }}" method="post">
                                @csrf
                                @method('delete')
                                <a href="/film/{{ $item->id }}" class="btn btn-info btn-sm">Detail</a>
                                <a href="{{ route('film.edit', $item->id) }}" class="btn btn-warning btn-sm">Edit</a>
                                <input type="submit" class="btn btn-danger btn-sm" value="delete">
                            </form>
                        @endauth
                        @guest
                            <a href="/film/{{ $item->id }}" class="btn btn-info btn-sm">Detail</a>
                        @endguest
                    </div>
                </div>
            </div>
        @empty
            <h1>TIDAK ADA FILM</h1>
        @endforelse
    </div>
@endsection